package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"onessh/internal/store"
)

func renderSSHConfigManagedBlock(cfg store.PlainConfig) string {
	aliases := make([]string, 0, len(cfg.Hosts))
	for alias := range cfg.Hosts {
		aliases = append(aliases, alias)
	}
	sort.Strings(aliases)

	var b strings.Builder
	b.WriteString(sshConfigManagedStart)
	b.WriteString("\n")
	b.WriteString("# generated by onessh\n")

	for _, alias := range aliases {
		host := cfg.Hosts[alias]
		userName, auth, err := resolveHostIdentity(cfg, host)
		if err != nil {
			continue
		}

		port := host.Port
		if port <= 0 {
			port = 22
		}

		b.WriteString("\n")
		b.WriteString("Host ")
		b.WriteString(alias)
		b.WriteString("\n")
		b.WriteString("  HostName ")
		b.WriteString(host.Host)
		b.WriteString("\n")
		if userName != "" {
			b.WriteString("  User ")
			b.WriteString(userName)
			b.WriteString("\n")
		}
		b.WriteString("  Port ")
		b.WriteString(strconv.Itoa(port))
		b.WriteString("\n")
		if host.ProxyJump != "" {
			b.WriteString("  ProxyJump ")
			b.WriteString(host.ProxyJump)
			b.WriteString("\n")
		}
		if strings.EqualFold(auth.Type, "key") && strings.TrimSpace(auth.KeyPath) != "" {
			b.WriteString("  IdentityFile ")
			b.WriteString(auth.KeyPath)
			b.WriteString("\n")
		}

		keys := sortedStringMapKeys(host.Env)
		for _, key := range keys {
			assignment := key + "=" + host.Env[key]
			b.WriteString("  SetEnv ")
			b.WriteString(sshConfigValueToken(assignment))
			b.WriteString("\n")
		}
	}

	b.WriteString(sshConfigManagedEnd)
	b.WriteString("\n")
	return b.String()
}

func upsertSSHConfigManagedBlock(existing, managedBlock string) string {
	start := strings.Index(existing, sshConfigManagedStart)
	end := strings.Index(existing, sshConfigManagedEnd)
	if start >= 0 && end > start {
		end += len(sshConfigManagedEnd)
		prefix := strings.TrimRight(existing[:start], "\n")
		suffix := strings.TrimLeft(existing[end:], "\n")
		var b strings.Builder
		if prefix != "" {
			b.WriteString(prefix)
			b.WriteString("\n\n")
		}
		b.WriteString(strings.TrimRight(managedBlock, "\n"))
		b.WriteString("\n")
		if suffix != "" {
			b.WriteString("\n")
			b.WriteString(suffix)
			if !strings.HasSuffix(suffix, "\n") {
				b.WriteString("\n")
			}
		}
		return b.String()
	}

	trimmed := strings.TrimRight(existing, "\n")
	if trimmed == "" {
		return managedBlock
	}
	return trimmed + "\n\n" + managedBlock
}

func writeTextFileAtomic(path string, data []byte, perm os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create directory for %s: %w", path, err)
	}

	tempFile, err := os.CreateTemp(filepath.Dir(path), ".onessh-*.tmp")
	if err != nil {
		return fmt.Errorf("create temp file for %s: %w", path, err)
	}
	tempName := tempFile.Name()

	cleanup := func() {
		_ = tempFile.Close()
		_ = os.Remove(tempName)
	}

	if err := tempFile.Chmod(perm); err != nil {
		cleanup()
		return fmt.Errorf("chmod temp file for %s: %w", path, err)
	}
	if _, err := tempFile.Write(data); err != nil {
		cleanup()
		return fmt.Errorf("write temp file for %s: %w", path, err)
	}
	if err := tempFile.Sync(); err != nil {
		cleanup()
		return fmt.Errorf("sync temp file for %s: %w", path, err)
	}
	if err := tempFile.Close(); err != nil {
		_ = os.Remove(tempName)
		return fmt.Errorf("close temp file for %s: %w", path, err)
	}
	if err := os.Rename(tempName, path); err != nil {
		_ = os.Remove(tempName)
		return fmt.Errorf("rename temp file for %s: %w", path, err)
	}
	if err := os.Chmod(path, perm); err != nil {
		return fmt.Errorf("chmod file %s: %w", path, err)
	}
	return nil
}
