# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Onessh < Formula
  desc "Encrypted SSH host manager with one master password"
  homepage "https://github.com/tiangong-dev/onessh"
  version "1.1.0"
  license "Unlicense"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tiangong-dev/onessh/releases/download/v1.1.0/onessh_1.1.0_darwin_amd64.tar.gz"
      sha256 "49e54a4e7397568103aae904be8195cf8588b2ecdb4e299702d334b53901043d"

      define_method(:install) do
        bin.install "onessh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tiangong-dev/onessh/releases/download/v1.1.0/onessh_1.1.0_darwin_arm64.tar.gz"
      sha256 "3cc84e3edcd06daab73ca360a6cfa19319bf558f841bac6d2296eaaa3a823b8a"

      define_method(:install) do
        bin.install "onessh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiangong-dev/onessh/releases/download/v1.1.0/onessh_1.1.0_linux_amd64.tar.gz"
      sha256 "00772004e5548a7e562ee66220523f22732b87537e92997bcb19329b0428c9c1"
      define_method(:install) do
        bin.install "onessh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiangong-dev/onessh/releases/download/v1.1.0/onessh_1.1.0_linux_arm64.tar.gz"
      sha256 "7074b3a10088bdb2cff53079d6ec0f56e914832b0f61e4f7363c9bbace98c2a3"
      define_method(:install) do
        bin.install "onessh"
      end
    end
  end

  test do
    system "#{bin}/onessh", "--help"
  end
end
