# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Onessh < Formula
  desc "Encrypted SSH host manager with one master password"
  homepage "https://github.com/tiangong-dev/onessh"
  version "0.0.0-test.20260304040024"
  license "Unlicense"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tiangong-dev/onessh/releases/download/v0.0.0-test.20260304040024/onessh_0.0.0-test.20260304040024_darwin_amd64.tar.gz"
      sha256 "6da008c13c861d5919750ff0a2badcb5762972a45b8d06e90580a396b1f436cb"

      define_method(:install) do
        bin.install "onessh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tiangong-dev/onessh/releases/download/v0.0.0-test.20260304040024/onessh_0.0.0-test.20260304040024_darwin_arm64.tar.gz"
      sha256 "fc56417a140a38d00bba28761792517e79702acc624ad2564cb9f4637897733d"

      define_method(:install) do
        bin.install "onessh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiangong-dev/onessh/releases/download/v0.0.0-test.20260304040024/onessh_0.0.0-test.20260304040024_linux_amd64.tar.gz"
      sha256 "ffb3cd59f95d3fc8b982242211c27d01aa0cab365d55b4a71f68b2aacdc07c3c"
      define_method(:install) do
        bin.install "onessh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tiangong-dev/onessh/releases/download/v0.0.0-test.20260304040024/onessh_0.0.0-test.20260304040024_linux_arm64.tar.gz"
      sha256 "ebc49071b85de2fa0bae7ece8c9c580612f875d72b74eabca31794f412aedb8e"
      define_method(:install) do
        bin.install "onessh"
      end
    end
  end

  test do
    system "#{bin}/onessh", "--help"
  end
end
